const CHAPTERS = [
  {
    id: 'equity', num: 1, icon: '💼', title: 'Equity',
    tag: 'Ownership and what it really means',
    scene: '💼🏢📊',
    dialogues: [
      { who: 'narrator', text: 'Alex has just arrived in FinCity. Before anything else, Finn wants to explain one foundational idea that underpins almost every investment.' },
      { who: 'finn', text: 'Welcome! Before we tour the markets, one word will come up constantly: EQUITY. Let\'s make sure you know exactly what it means. Tell me — if you own a house worth $300,000 but have a $200,000 mortgage, what do YOU actually own?' },
      { who: 'alex', text: 'I guess… only the part that\'s mine? $100,000 worth?' },
      { who: 'finn', text: 'Exactly. That $100,000 is your EQUITY. It\'s the portion you truly own after subtracting what you owe. The formula is simple: Equity = Assets − Liabilities. The same idea applies to companies, banks, and investment portfolios.' },
      { who: 'alex', text: 'So for a company, equity is what\'s left after paying all debts?' },
      { who: 'finn', text: 'Precisely. If a company owns $500,000 in assets (buildings, cash, equipment) and owes $300,000 to banks and creditors, the SHAREHOLDERS\' EQUITY is $200,000. That $200,000 belongs to the owners — the shareholders. When you buy a stock, you\'re buying a slice of that equity.' },
      { who: 'alex', text: 'What\'s the difference between book value and market value of equity?' },
      { who: 'finn', text: 'BOOK VALUE is equity on the accounting balance sheet — historical cost of assets minus liabilities. MARKET VALUE is what investors are actually willing to pay, based on expectations of future profits. Apple\'s book value might be $60 billion, but investors pay $3 trillion for its shares because they expect massive future profits.' },
      { who: 'alex', text: 'So a company can be worth far more than its accounting numbers suggest?' },
      { who: 'finn', text: 'Always. The gap between book and market value reflects intangibles: brand, talent, patents, competitive advantage. Google\'s search algorithm has no book value — yet it\'s worth hundreds of billions. Markets price the FUTURE; accountants record the PAST.' },
      { who: 'alex', text: 'How do companies raise equity? Is it just selling shares?' },
      { who: 'finn', text: 'That\'s the main way. A company issues shares, investors buy them, cash flows in — that\'s EQUITY FINANCING. The alternative is DEBT FINANCING: borrow money from a bank or issue bonds. The key difference: equity holders OWN the company and share in profits. Debt holders are just creditors who get paid back with interest.' },
      { who: 'alex', text: 'Which is better — equity or debt financing?' },
      { who: 'finn', text: 'It depends! Debt is cheaper (interest is tax-deductible, lenders take less risk) but dangerous if the company struggles to make payments. Equity never needs repaying but dilutes the founders\' ownership. Most companies use a MIX — a capital structure that balances the benefits of both.' },
      { who: 'narrator', text: 'Equity is the foundational concept of the entire investment world. Every stock you buy is a share of equity. Every company balance sheet starts with Assets = Liabilities + Equity. Mastering this one idea unlocks everything else.' },
    ],
    concept: 'Equity = Assets − Liabilities. It represents ownership. Shareholders\' equity is what investors would receive if a company sold everything and paid all debts. Book value vs market value: markets price the future, accountants record the past.',
    quiz: [
      { q: 'A company has $800,000 in assets and $550,000 in liabilities. What is the shareholders\' equity?', opts: ['$250,000', '$800,000', '$550,000', '$1,350,000'], ans: 0, exp: 'Shareholders\' equity = Assets − Liabilities = $800,000 − $550,000 = $250,000. This is what belongs to the owners after all debts are paid.' },
      { q: 'Apple\'s book value is $70B but its market cap is $3T. What explains the difference?', opts: ['Investors price future earnings, brand, and intangibles not on the balance sheet', 'Apple has hidden assets', 'The stock market is always wrong', 'Book value includes goodwill'], ans: 0, exp: 'Market value reflects expectations about future profits, brand strength, competitive moats, and growth — none of which appear on an accounting balance sheet. Markets are forward-looking.' }
    ]
  },
  {
    id: 'stock-market', num: 2, icon: '🏦', title: 'The Stock Market',
    tag: 'Own a slice of any company',
    scene: '🌆🏪🍌',
    dialogues: [
      { who: 'narrator', text: 'Alex just arrived in FinCity for the very first time — a city where money, markets, and opportunity come alive. Guide Finn the Fox trots over with a big smile.' },
      { who: 'finn', text: 'Welcome to FinCity! Before we talk about the stock market, let\'s start with something really simple. Do you know what a company actually IS?' },
      { who: 'alex', text: 'It\'s... a business? Like a shop or a factory?' },
      { who: 'finn', text: 'Exactly. See that banana stand over there? That\'s BananaCo. The owner started it with their own money, built it up, and now the entire business — the stand, the bananas, all future profits — is worth $10,000. That total worth is called the company\'s VALUE.' },
      { who: 'alex', text: 'Okay, so BananaCo is worth $10,000. What does the stock market have to do with that?' },
      { who: 'finn', text: 'Here\'s where it gets interesting. The owner decided to slice that $10,000 value into 1,000 equal tiny pieces. Each piece is called a SHARE (or a STOCK). So: 1,000 shares × $10 each = $10,000 total. Anyone can buy these pieces!' },
      { who: 'alex', text: 'If I buy one share for $10, I own one tiny piece of BananaCo?' },
      { who: 'finn', text: 'Yes! 1 share out of 1,000 = 0.1% ownership. Buy 100 shares ($1,000) and you own 10% of BananaCo. You\'re literally a part-owner of that banana business — a SHAREHOLDER.' },
      { who: 'alex', text: 'Why would the owner sell pieces of their own company? Wouldn\'t they lose control?' },
      { who: 'finn', text: 'They do it to raise MONEY. Opening more stands, buying better equipment, hiring staff — all of that costs money. Instead of a bank loan, they sell shares. Investors give them cash upfront and become co-owners. As long as the owner keeps more than 50% of shares, they keep control.' },
      { who: 'alex', text: 'And what do I get as an investor who buys shares?' },
      { who: 'finn', text: 'Two things! If BananaCo grows and doubles in value to $20,000, your shares double too — your $100 becomes $200. And if they earn profits, they might share some with you as DIVIDENDS (we\'ll cover that soon!).' },
      { who: 'alex', text: 'What if BananaCo does badly? Like, nobody wants bananas anymore?' },
      { who: 'finn', text: 'Then the share price falls. If the company is now only worth $5,000, your shares are worth half what you paid. You could LOSE money. That\'s the RISK of investing — and why understanding what you\'re buying matters so much.' },
      { who: 'narrator', text: 'The STOCK MARKET is the place — now mostly digital — where all these shares are listed, bought, and sold every day, with prices changing by the second based on supply and demand.' },
    ],
    concept: 'A stock is a share of ownership in a company. Companies sell shares to raise money. Investors buy shares hoping the company grows — making the shares worth more.',
    quiz: [
      { q: 'BananaCo is worth $10,000 and split into 1,000 shares. If you buy 50 shares, what % of the company do you own?', opts: ['5%', '10%', '50%', '0.5%'], ans: 0, exp: '50 ÷ 1000 = 5%. Ownership = shares you hold ÷ total shares × 100.' },
      { q: 'Why do companies sell shares on the stock market?', opts: ['To raise money for growth', 'To give away free money', 'To pay taxes', 'To track customers'], ans: 0, exp: 'Companies sell shares (go public) to raise capital — money they can use to expand, hire, or invest without taking loans.' }
    ]
  },
  {
    id: 'inflation', num: 3, icon: '🔺', title: 'Inflation',
    tag: 'Why your money loses value over time',
    scene: '🔺🛒💵',
    dialogues: [
      { who: 'narrator', text: 'Finn takes Alex to a FinCity grocery store. A coffee costs $4 today. Finn pulls out an old receipt.' },
      { who: 'finn', text: 'This receipt is from 10 years ago. The same coffee cost $2.50 then. It\'s the same coffee, the same shop. But the price doubled. What happened?' },
      { who: 'alex', text: 'Prices just… went up? Is that inflation?' },
      { who: 'finn', text: 'Exactly! INFLATION is the rate at which prices across an economy rise over time — which means your money\'s PURCHASING POWER falls. If inflation is 5%, $100 today will only buy what $95 bought last year. Your cash is literally losing value while sitting in your wallet.' },
      { who: 'alex', text: 'How do we measure inflation? Whose prices do we track?' },
      { who: 'finn', text: 'Governments track a "basket" of typical goods and services — food, rent, transport, clothing, healthcare. This is the CONSUMER PRICE INDEX (CPI). Each month, statisticians check prices on hundreds of items. If the basket costs 4% more than a year ago, inflation is 4%.' },
      { who: 'alex', text: 'What actually causes inflation? Why do prices rise?' },
      { who: 'finn', text: 'Three main causes. DEMAND-PULL: everyone has money and wants stuff — too much demand, prices rise. COST-PUSH: production costs rise (oil, wages) — companies pass costs to customers. MONETARY: the government prints too much money — more dollars chasing the same goods means each dollar is worth less.' },
      { who: 'alex', text: 'Which is happening most often in the real world?' },
      { who: 'finn', text: 'Usually a mix! The 2021–2022 inflation spike was all three: COVID stimulus flooded the economy with cash (monetary), supply chains broke (cost-push), and reopening triggered a spending surge (demand-pull). Central banks fought it by raising interest rates sharply.' },
      { who: 'alex', text: 'If I have $10,000 in a savings account paying 1% interest and inflation is 4%, what actually happens?' },
      { who: 'finn', text: 'You\'re LOSING purchasing power. Your account shows $10,100 after a year — a "gain" of $100. But goods cost 4% more. In REAL terms, your $10,100 can only buy what $9,710 bought a year ago. Your REAL return is −3%. Inflation silently erodes savings in accounts that don\'t keep up.' },
      { who: 'alex', text: 'So how do investors protect themselves from inflation?' },
      { who: 'finn', text: 'STOCKS historically beat inflation over time — companies raise prices, so their revenues and profits grow with inflation. REAL ASSETS like property, commodities, and gold tend to hold value. TIPS (Treasury Inflation-Protected Securities) are bonds specifically designed to rise with inflation. Cash is the worst inflation hedge.' },
      { who: 'alex', text: 'What\'s the ideal inflation rate? Is zero best?' },
      { who: 'finn', text: 'Surprisingly, no! Central banks target around 2% inflation — low enough to preserve purchasing power, but enough to keep the economy moving. Zero inflation risks DEFLATION (falling prices), which causes people to delay spending (why buy today if it\'s cheaper tomorrow?), and can trigger recessions. 2% is the Goldilocks zone.' },
      { who: 'narrator', text: 'Inflation is the invisible tax on savers. Understanding it is critical: every investment decision — from choosing between stocks and bonds to how long you hold cash — must account for inflation eroding your real returns.' },
    ],
    concept: 'Inflation = rate of price increase over time. CPI measures it. Real return = nominal return minus inflation. Stocks, real assets, and TIPS hedge inflation. Cash loses purchasing power. Central banks target ~2% inflation.',
    quiz: [
      { q: 'Your savings account pays 1.5% interest. Inflation is 4%. What is your real return?', opts: ['−2.5%', '+5.5%', '+1.5%', '+4%'], ans: 0, exp: 'Real return = Nominal return − Inflation = 1.5% − 4% = −2.5%. Despite the account growing in dollar terms, you can buy less than before.' },
      { q: 'Which asset class historically provides the best long-term inflation protection?', opts: ['Stocks (equities)', 'Cash in a savings account', 'Short-term government bonds', 'Foreign currencies'], ans: 0, exp: 'Stocks represent ownership in companies that can raise prices with inflation, growing revenues and profits. Over long periods, equity returns have significantly outpaced inflation in most developed markets.' }
    ]
  },
  {
    id: 'bonds', num: 4, icon: '🔗', title: 'Bonds',
    tag: 'Lending money and earning interest',
    scene: '🔗📄💰',
    dialogues: [
      { who: 'narrator', text: 'FinCity\'s government needs to build a new bridge but doesn\'t have the money. Finn takes Alex to the FinCity Bond Office to see how governments — and companies — borrow from the public.' },
      { who: 'finn', text: 'Imagine the city needs $1 million to build a bridge. Rather than getting one big bank loan, they ask thousands of ordinary investors to each lend them a small amount. That\'s what a BOND is — a loan from investors to a borrower, documented as a tradeable security.' },
      { who: 'alex', text: 'So a bond is basically an IOU from a government or company?' },
      { who: 'finn', text: 'Exactly! When you buy a $1,000 bond from FinCity at 5% for 10 years, you\'re lending them $1,000. They promise to pay you $50 per year (the COUPON) for 10 years, then return your $1,000 (the FACE VALUE or PRINCIPAL) at MATURITY. Simple, predictable cash flows.' },
      { who: 'alex', text: 'What\'s the difference between a coupon and a yield?' },
      { who: 'finn', text: 'The COUPON RATE is fixed at issuance — the 5% in our example. The YIELD is what you actually earn based on the price you pay. If that bond\'s price falls to $900 in the market (you can buy it cheaper), the same $50 coupon gives you a yield of 5.56% — more bang for your buck!' },
      { who: 'alex', text: 'Why would the price of a bond change at all? Isn\'t it fixed?' },
      { who: 'finn', text: 'The FACE VALUE is fixed, but the MARKET PRICE moves constantly. Here\'s the key rule: when interest rates RISE, existing bond prices FALL. Think about it — if new bonds now pay 7%, who wants your old 5% bond? They\'ll only buy it at a discount. Rates up → bond prices down. Always.' },
      { who: 'alex', text: 'And if interest rates fall, bond prices rise?' },
      { who: 'finn', text: 'Yes! If rates fall to 3%, your 5% bond is suddenly very attractive — better than anything new in the market. Investors bid up its price. This is why bond fund managers obsess over interest rate predictions — they determine whether bond portfolios gain or lose value.' },
      { who: 'alex', text: 'What\'s the difference between government bonds and corporate bonds?' },
      { who: 'finn', text: 'GOVERNMENT BONDS (Treasuries in the US, Gilts in the UK) are issued by national governments. They\'re considered the safest investment — governments can always raise taxes or theoretically print money to repay. CORPORATE BONDS are riskier (companies can go bankrupt), so they pay a higher yield as compensation for that extra risk.' },
      { who: 'alex', text: 'How do I know how risky a bond is?' },
      { who: 'finn', text: 'Credit rating agencies — Moody\'s, S&P, Fitch — rate bonds from AAA (safest, lowest yield) down to D (defaulted). Investment-grade bonds (BBB or above) are considered relatively safe. Below BBB are "junk bonds" — higher yield, much higher default risk. Always check the rating.' },
      { who: 'alex', text: 'Why would anyone want a bond when stocks give higher returns over time?' },
      { who: 'finn', text: 'Stability and income! Bonds provide predictable cash flows, don\'t crash 40% in a recession (usually), and are a critical part of a balanced portfolio. Near retirement? You can\'t afford to see your savings halved by a stock crash. Bonds smooth out that volatility. Most professional portfolios hold both.' },
      { who: 'narrator', text: 'Bonds are the backbone of global finance — governments and corporations raise trillions through them every year. The bond market is actually BIGGER than the stock market. Understanding yield, duration, and credit risk is essential for any serious investor.' },
    ],
    concept: 'A bond is a loan to a government or company. You receive coupon payments + face value at maturity. Key rule: rates up → bond prices down. Credit ratings measure default risk. Bonds provide stability vs stocks.',
    quiz: [
      { q: 'You own a bond with a $1,000 face value and 4% coupon. Interest rates rise to 6%. What happens to your bond\'s market price?', opts: ['It falls below $1,000', 'It rises above $1,000', 'It stays at $1,000', 'It depends on maturity only'], ans: 0, exp: 'When market rates rise above the bond\'s coupon, the bond becomes less attractive. Its price falls so that the fixed coupon payments represent a competitive yield for the buyer.' },
      { q: 'A corporate bond pays 8% yield, a government bond pays 3%. What explains the difference?', opts: ['The corporate bond has higher default risk', 'The corporate bond has lower risk', 'Government bonds are longer maturity', 'Corporate bonds are taxed differently'], ans: 0, exp: 'The extra 5% yield is a RISK PREMIUM — compensation for the higher chance the corporation defaults vs the government. Higher risk = higher yield required to attract investors.' }
    ]
  },
  {
    id: 'credit', num: 5, icon: '💳', title: 'Credit',
    tag: 'The price of trust in borrowing',
    scene: '💳🏦📊',
    dialogues: [
      { who: 'narrator', text: 'Alex needs $50,000 to open a new business in FinCity. Two lenders quote very different interest rates. Finn explains why.' },
      { who: 'finn', text: 'Lender A quotes 4% interest. Lender B quotes 11%. Same loan amount, but wildly different rates. Why? It all comes down to CREDIT — the perceived ability and willingness of a borrower to repay a debt.' },
      { who: 'alex', text: 'So the interest rate I get depends on how trustworthy I am as a borrower?' },
      { who: 'finn', text: 'Exactly. Lenders assess CREDIT RISK — the probability that you won\'t repay. Lower risk = lower interest rate (you\'re a reliable borrower). Higher risk = higher rate (the lender demands compensation for the chance you default). Credit is essentially a measurement of financial trust.' },
      { who: 'alex', text: 'How is creditworthiness actually measured?' },
      { who: 'finn', text: 'For individuals: a CREDIT SCORE (300–850 in the US). It\'s calculated from payment history, amounts owed, length of credit history, new credit, and types of credit used. Pay bills on time, keep debt low, and your score rises. Miss payments or max out cards, and it tanks.' },
      { who: 'alex', text: 'What about companies and governments? How are they rated?' },
      { who: 'finn', text: 'CREDIT RATING AGENCIES — Moody\'s, Standard & Poor\'s, and Fitch — analyse company and government finances and assign letter grades. AAA is the highest (rock-solid, like US Treasury). BBB is the minimum "investment grade." Below BBB is "speculative" or JUNK status — high default risk.' },
      { who: 'alex', text: 'What actually happens if a borrower defaults — stops paying?' },
      { who: 'finn', text: 'For the borrower: bankruptcy, ruined credit score, seized assets, legal action. For the LENDER: they lose part or all of the money owed. This is why lenders price risk into interest rates — the higher the chance of default, the more they charge upfront to compensate for potential losses.' },
      { who: 'alex', text: 'What is a credit spread?' },
      { who: 'finn', text: 'The CREDIT SPREAD is the extra yield a borrower pays ABOVE a risk-free rate (like US Treasuries). A AAA corporate bond might pay 3.5% while Treasuries pay 3% — credit spread of 0.5%. A junk bond might pay 9% — spread of 6%. The spread is the market\'s real-time price tag on default risk.' },
      { who: 'alex', text: 'Can credit ratings change over time?' },
      { who: 'finn', text: 'Absolutely — and when they do, it matters enormously. A DOWNGRADE (e.g., from BBB to BB) below investment grade forces many institutional investors to SELL the bond (their mandates prohibit junk). This selling floods the market, crashing the bond\'s price. Credit events can cause violent moves in bond markets.' },
      { who: 'alex', text: 'What\'s a credit default swap? I hear this in financial news.' },
      { who: 'finn', text: 'A CREDIT DEFAULT SWAP (CDS) is essentially insurance on a bond. You pay a premium; if the bond issuer defaults, the CDS seller pays you the face value. Banks and hedge funds use CDS to either hedge credit risk or speculate on companies failing. They became famous in the 2008 crisis when AIG wrote billions in CDS it couldn\'t pay.' },
      { who: 'narrator', text: 'Credit is the lifeblood of a modern economy — mortgages, business loans, car finance, government debt. Understanding how risk gets priced into interest rates helps you understand why different borrowers face wildly different costs for the same dollar borrowed.' },
    ],
    concept: 'Credit measures a borrower\'s ability to repay. Credit scores (individuals) and credit ratings AAA→D (companies/governments) determine interest rates. Credit spread = extra yield above risk-free rate. Higher default risk = higher borrowing cost.',
    quiz: [
      { q: 'Company X has a BBB credit rating. Company Y has a BB rating (one notch lower, "junk"). Who pays a higher interest rate on new bonds?', opts: ['Company Y pays more', 'Company X pays more', 'They pay the same', 'Rating doesn\'t affect interest rates'], ans: 0, exp: 'Lower credit rating = higher default risk = lenders demand a higher yield as compensation. Junk-rated companies can pay 3–8% more annually than investment-grade peers for the same loan amount.' },
      { q: 'What is a "credit spread"?', opts: ['The extra yield a bond pays above the risk-free rate', 'The bid-ask spread on credit cards', 'The difference between short and long-term rates', 'A type of credit default swap'], ans: 0, exp: 'Credit spread = bond yield minus the risk-free rate (government bond). It represents the market\'s price for default risk. Spreads widen during crises (higher fear) and narrow in calm periods.' }
    ]
  },
  {
    id: 'taxes', num: 6, icon: '🧾', title: 'Taxes on Investments',
    tag: 'The return you keep is what matters',
    scene: '🧾💸📋',
    dialogues: [
      { who: 'narrator', text: 'Alex just made $5,000 profit selling BananaCo shares. Finn shows up with some sobering news before Alex spends it all.' },
      { who: 'finn', text: 'Congratulations on the profit! But before you celebrate — the government wants their share. Investment income is taxed. How MUCH you pay depends on several things, and understanding this can literally mean thousands of dollars more in your pocket.' },
      { who: 'alex', text: 'So I don\'t keep the full $5,000 profit?' },
      { who: 'finn', text: 'Likely not. Investment gains are subject to CAPITAL GAINS TAX — tax on profits from selling an asset. But here\'s the critical detail: the rate depends on HOW LONG you held the asset. Two completely different rates: short-term and long-term.' },
      { who: 'alex', text: 'What\'s the difference?' },
      { who: 'finn', text: 'SHORT-TERM capital gains: held less than 1 year. Taxed at your ORDINARY INCOME tax rate — could be 22%, 24%, even 37% depending on your bracket. LONG-TERM capital gains: held MORE than 1 year. Taxed at preferential rates: 0%, 15%, or 20% depending on income. The tax code literally rewards patient investors.' },
      { who: 'alex', text: 'So if I hold for 12 months and one day instead of 11 months, I could save a massive amount of tax?' },
      { who: 'finn', text: 'Exactly! On a $50,000 gain in the 32% bracket: short-term tax = $16,000. Long-term tax = $7,500 (at 15%). Waiting that extra month saved $8,500. This is called TAX-EFFICIENCY — structuring your investing to legally minimise the tax you pay.' },
      { who: 'alex', text: 'What about dividends? Are those taxed differently too?' },
      { who: 'finn', text: 'Yes. QUALIFIED DIVIDENDS (from most US stocks held long enough) are taxed at the same low long-term capital gains rates. ORDINARY DIVIDENDS are taxed as income. And interest from bonds is taxed as ordinary income at the full rate — which is one reason some investors prefer dividend stocks over bonds in taxable accounts.' },
      { who: 'alex', text: 'Is there any way to avoid paying tax on investments entirely?' },
      { who: 'finn', text: 'Not avoid — but defer or eliminate through TAX-ADVANTAGED ACCOUNTS. A 401(k) or Traditional IRA: contributions are pre-tax, investments grow tax-deferred, you pay tax only when you withdraw in retirement. A ROTH IRA: contributions are after-tax, but ALL gains grow and are withdrawn TAX-FREE. The math on Roth compounding is incredible over decades.' },
      { who: 'alex', text: 'What is tax-loss harvesting? I\'ve heard that term.' },
      { who: 'finn', text: 'TAX-LOSS HARVESTING is intentionally selling investments that are DOWN to realise a loss — which offsets your gains and reduces tax. If you made $10,000 profit on BananaCo but $4,000 loss on OilCo, you only pay tax on $6,000 net gain. You can harvest up to $3,000 in losses annually against ordinary income too.' },
      { who: 'alex', text: 'This all sounds complex. Do I need an accountant?' },
      { who: 'finn', text: 'For complex portfolios — yes. But the core principles are simple: hold investments long-term, use tax-advantaged accounts first, harvest losses strategically. A financial advisor estimates that tax optimisation alone can add 1–2% per year to your effective return. Over 30 years, that compounds into a HUGE difference.' },
      { who: 'narrator', text: 'Taxes are the most controllable cost in investing. You can\'t control market returns, but you CAN control when and how you realise gains. The best investors treat their after-tax return as the only return that matters.' },
    ],
    concept: 'Short-term gains (< 1 year) taxed as income. Long-term gains (> 1 year) taxed at lower rates (0/15/20%). Tax-advantaged accounts (401k, Roth IRA) shelter gains. Tax-loss harvesting offsets gains with losses. After-tax return is what actually matters.',
    quiz: [
      { q: 'You\'re in the 24% income tax bracket and sell stock for a $20,000 gain. You held it for 8 months. Approx how much tax do you owe?', opts: ['$4,800 (short-term rate)', '$3,000 (15% long-term rate)', '$0 — stocks aren\'t taxed', '$7,400'], ans: 0, exp: 'Held less than 12 months = short-term capital gain, taxed at your ordinary income rate of 24%. $20,000 × 24% = $4,800. Holding 4+ more months would have cut this to $3,000 at the 15% long-term rate.' },
      { q: 'What is the key advantage of a Roth IRA account for investing?', opts: ['Gains grow and are withdrawn completely tax-free', 'You pay no taxes at all ever', 'Contributions are tax-deductible', 'There are no contribution limits'], ans: 0, exp: 'In a Roth IRA, you invest after-tax dollars. All growth and qualified withdrawals in retirement are 100% tax-free. Over decades, this can shelter hundreds of thousands in gains from taxation.' }
    ]
  },
  {
    id: 'bid-ask', num: 7, icon: '💱', title: 'Bid & Ask',
    tag: 'How prices are actually set',
    scene: '🏪🤝💰',
    dialogues: [
      { who: 'narrator', text: 'Alex wanders to the FinCity Auction Hall. Hundreds of buyers and sellers are shouting prices at each other. It looks chaotic — but Finn says there\'s a perfect system underneath.' },
      { who: 'finn', text: 'Before we dive in, a simple question: if you were selling your old bike and someone offered you $80 for it, but you wanted $100 — what would happen?' },
      { who: 'alex', text: 'We\'d probably negotiate... maybe settle on $90?' },
      { who: 'finn', text: 'Exactly! You had an ASKING price (the minimum you\'d accept) and they had a BIDDING price (the maximum they\'d pay). In the stock market, this same tug-of-war happens millions of times a day, automatically.' },
      { who: 'alex', text: 'So the "bid" is what buyers are offering to pay right now?' },
      { who: 'finn', text: 'Right. The BID is the highest price any buyer is currently willing to pay. Right now, the best bid for BananaCo is $48 — someone is saying "I\'ll pay up to $48 per share, not a cent more."' },
      { who: 'alex', text: 'And the "ask" is the sellers\' side?' },
      { who: 'finn', text: 'Exactly. The ASK (also called "offer") is the lowest price any seller will currently accept — $52. The gap between them is the SPREAD: $52 − $48 = $4. A deal doesn\'t happen yet because buyers and sellers haven\'t agreed.' },
      { who: 'alex', text: 'So if I want to buy a share RIGHT NOW, which price do I pay?' },
      { who: 'finn', text: 'You pay the ASK — $52. Because the cheapest a seller will go is $52. If you want to SELL right now, you get the BID — $48. You\'re accepting what the highest buyer is currently offering.' },
      { who: 'alex', text: 'That means if I buy at $52 and immediately sell, I only get $48 back? I lose $4 instantly?' },
      { who: 'finn', text: 'Yes! That\'s the cost of trading. The $4 goes to the MARKET MAKER — a professional trader who sits between buyers and sellers. They buy at the bid ($48) and sell at the ask ($52), pocketing the spread. In return, they always provide quotes so you can always trade instantly.' },
      { who: 'alex', text: 'So is a bigger spread worse for me as a regular investor?' },
      { who: 'finn', text: 'Yes! Tighter spreads = lower trading costs. Popular stocks like Apple have spreads of just $0.01 because so many people trade them. Rare or thinly-traded stocks might have $2–$5 spreads. Always check the spread before trading — it\'s a hidden cost most beginners completely miss.' },
    ],
    concept: 'Bid = highest price a buyer will pay. Ask = lowest price a seller will accept. Spread = Ask − Bid. If you want to buy immediately, you pay the Ask. If you want to sell immediately, you get the Bid.',
    quiz: [
      { q: 'The bid price is $95 and the ask price is $97. What is the spread?', opts: ['$2', '$95', '$97', '$192'], ans: 0, exp: 'Spread = Ask − Bid = $97 − $95 = $2. This $2 is the market maker\'s profit per round-trip.' },
      { q: 'If you want to BUY a stock RIGHT NOW (not wait), which price do you pay?', opts: ['The Ask price', 'The Bid price', 'The midpoint', 'The spread'], ans: 0, exp: 'When buying immediately (market order), you pay the Ask — the lowest price a seller is willing to accept right now.' }
    ]
  },
  {
    id: 'trading', num: 8, icon: '⚡', title: 'Trading',
    tag: 'How to buy and sell',
    scene: '💻📊🔔',
    dialogues: [
      { who: 'narrator', text: 'Alex enters the FinCity Exchange — a buzzing trading floor with screens everywhere showing live prices.' },
      { who: 'finn', text: 'So you\'ve decided to buy BananaCo shares. You open your trading app and see a "Buy" button. Seems simple, right? But HOW you place that order makes a huge difference to the price you actually get.' },
      { who: 'alex', text: 'I thought you just click "buy" and you own shares?' },
      { who: 'finn', text: 'You do — but there are different TYPES of buy orders, each with trade-offs. The simplest is a MARKET ORDER. It says: "Buy me 10 shares RIGHT NOW at whatever price the market is offering." It fills instantly.' },
      { who: 'alex', text: 'Sounds perfect. What\'s the downside?' },
      { who: 'finn', text: 'You give up price control. If BananaCo is at $50 but the market is moving fast, by the time your order fills it might be $51 or $52. That gap between what you expected and what you got is called SLIPPAGE. For small calm trades it\'s fine — but on big or fast-moving stocks it can cost you.' },
      { who: 'alex', text: 'What if I only want to buy at exactly $45 — not a cent more?' },
      { who: 'finn', text: 'Then use a LIMIT ORDER. You tell the system: "Only buy BananaCo if the price drops to $45 or lower." Your order joins a queue and WAITS. The moment the stock hits $45, your order fills automatically at that price.' },
      { who: 'alex', text: 'So I get the exact price I want — but I might wait forever and it never fills?' },
      { who: 'finn', text: 'Exactly the trade-off: market orders guarantee EXECUTION but not price. Limit orders guarantee PRICE but not execution. If BananaCo never drops to $45, you don\'t get the shares — but you also don\'t lose any money.' },
      { who: 'alex', text: 'What about protecting myself after I own shares, if the price starts falling?' },
      { who: 'finn', text: 'That\'s where STOP ORDERS come in. You own BananaCo at $50. Set a stop at $42: "If the price ever falls to $42, automatically sell." It becomes a market order the moment that price is hit — like a safety net that exits you automatically before losses get worse.' },
      { who: 'alex', text: 'So market orders are fast, limit orders are precise, and stop orders are protective?' },
      { who: 'finn', text: 'Perfect summary! Professionals combine all three: buy with a limit order for a good entry price, set a stop order to cap losses, use market orders when speed matters more than price. Having a plan before you trade is what separates investors from gamblers.' },
    ],
    concept: 'Market Order: fill immediately at best available price. Limit Order: only fill if price reaches your target. Stop Order: triggers when price crosses a threshold — used to limit losses.',
    quiz: [
      { q: 'You set a LIMIT BUY order for BananaCo at $44. The stock is currently at $50. When does your order execute?', opts: ['When the price falls to $44', 'Immediately at $50', 'Never', 'At market close'], ans: 0, exp: 'A limit buy order only executes when the stock price falls to (or below) your specified limit price of $44.' },
      { q: 'What is a key risk of using a Market Order?', opts: ['You might pay more than expected (slippage)', 'Your order might never fill', 'It costs extra fees always', 'It can only be used at market open'], ans: 0, exp: 'Market orders fill immediately but at the current market price — which can be worse than you expected, especially for illiquid stocks. This is called slippage.' }
    ]
  },
  {
    id: 'dividends', num: 9, icon: '💸', title: 'Dividends',
    tag: 'Getting paid to own shares',
    scene: '🍌💰📬',
    dialogues: [
      { who: 'narrator', text: 'Three months after buying BananaCo shares, Alex gets an unexpected envelope in the mail...' },
      { who: 'alex', text: 'Finn! BananaCo sent me $50 and I didn\'t sell anything. What is this?!' },
      { who: 'finn', text: 'Congratulations — that\'s a DIVIDEND! But let\'s understand where that money comes from. When a company earns more money than it spends in a period, that extra is called PROFIT (or EARNINGS).' },
      { who: 'alex', text: 'Okay, so BananaCo made a profit. What do they usually do with it?' },
      { who: 'finn', text: 'A company has two main choices: reinvest it back into the business (open more stands, buy equipment, hire people) — or share some of it with shareholders. When they share profits with shareholders, those payments are called DIVIDENDS.' },
      { who: 'alex', text: 'So BananaCo declared $1 dividend per share, I own 50 shares, so I get $50?' },
      { who: 'finn', text: 'Exactly right! 50 × $1 = $50. Just for HOLDING the shares — you didn\'t have to do anything. This is called PASSIVE INCOME. You own a piece of the business, and the business pays you a share of its profits.' },
      { who: 'alex', text: 'Do all companies pay dividends?' },
      { who: 'finn', text: 'No — and this is important. Young, fast-growing companies (think early Amazon or Tesla) usually don\'t pay dividends. They reinvest every dollar to grow faster. Shareholders make money through rising stock prices instead.' },
      { who: 'alex', text: 'Which types of companies DO pay dividends then?' },
      { who: 'finn', text: 'Stable, mature businesses — banks, utilities, consumer goods companies. Coca-Cola has paid dividends every single year for decades. They\'re past rapid growth, so they return profits to shareholders instead of reinvesting.' },
      { who: 'alex', text: 'How do I compare dividends across different stocks?' },
      { who: 'finn', text: 'Use the DIVIDEND YIELD: Annual Dividend ÷ Share Price × 100%. Stock costs $100 and pays $4/year? Yield = 4%. A yield above 5% is considered high — but be careful, a very high yield can signal the company is struggling and may cut the dividend soon!' },
      { who: 'alex', text: 'Can I reinvest dividends automatically to buy more shares?' },
      { who: 'finn', text: 'Yes! It\'s called a DRIP — Dividend Reinvestment Plan. Instead of taking the cash, dividends automatically buy more shares. Over decades, this turbocharges compounding: more shares → more dividends → even more shares. It\'s one of the most powerful wealth-building tools available.' },
    ],
    concept: 'Dividends are cash payments companies make to shareholders from profits. Dividend Yield = Annual Dividend ÷ Share Price × 100%. Companies that pay consistent dividends are often seen as stable investments.',
    quiz: [
      { q: 'A stock is priced at $200 and pays an annual dividend of $8 per share. What is the dividend yield?', opts: ['4%', '8%', '2%', '40%'], ans: 0, exp: 'Dividend Yield = $8 ÷ $200 × 100 = 4%. This means for every $100 invested, you earn $4/year in dividends.' },
      { q: 'Why might a fast-growing tech startup NOT pay dividends?', opts: ['They reinvest all profits to grow faster', 'They are too small', 'Dividends are illegal for tech companies', 'They prefer stock buybacks always'], ans: 0, exp: 'Growth companies typically reinvest profits back into expansion (R&D, hiring, marketing) rather than distributing cash. Shareholders benefit through rising stock prices instead.' }
    ]
  },
  {
    id: 'portfolio', num: 10, icon: '🗂️', title: 'Portfolio',
    tag: 'Don\'t put all eggs in one basket',
    scene: '🧺🍌🥇⛽',
    dialogues: [
      { who: 'narrator', text: 'Alex made a great profit on BananaCo and now has $1,000 to invest. They\'re about to put it ALL into BananaCo — but Finn stops them.' },
      { who: 'finn', text: 'Wait! Before you do that, let me tell you a story. Imagine you\'re a farmer. You plant ALL your crops in one single field. A flood hits — you lose EVERYTHING. But if you\'d split your crops across five different fields...' },
      { who: 'alex', text: 'Only one field floods, and you still have four others producing!' },
      { who: 'finn', text: 'That\'s DIVERSIFICATION — the single most important concept in investing. Never put all your money in one place. Your total collection of investments is called your PORTFOLIO.' },
      { who: 'alex', text: 'So instead of $1,000 in BananaCo, I should spread it around?' },
      { who: 'finn', text: 'Exactly. Split it: $400 in BananaCo stock, $200 in GoldCorp, $150 in OilPlus Energy, $150 in FinCity Government Bonds, $100 in cash. Now no single disaster can wipe you out.' },
      { who: 'alex', text: 'Why does spreading across DIFFERENT types help? Can\'t all stocks fall together?' },
      { who: 'finn', text: 'They can — but different ASSET CLASSES behave differently. When stocks crash, gold often rises (it\'s a "safe haven"). Bonds often go up when stocks go down. When assets don\'t move together, they have LOW CORRELATION. Low correlation = better diversification.' },
      { who: 'alex', text: 'What are the main asset classes I should know about?' },
      { who: 'finn', text: 'Four main ones: STOCKS (ownership in companies — high risk, high potential return), BONDS (loans to governments or companies — lower risk, steady return), REAL ESTATE (property — inflation hedge), and CASH. Most portfolios mix stocks and bonds as the core.' },
      { who: 'alex', text: 'What\'s the right split for me?' },
      { who: 'finn', text: 'That depends on your RISK TOLERANCE — how much potential loss you can stomach. Young investors with decades ahead can afford more risk (80% stocks). Near retirement? Shift to stability (more bonds). This decision — your mix — is called ASSET ALLOCATION.' },
      { who: 'alex', text: 'Is there a simple rule of thumb for beginners?' },
      { who: 'finn', text: 'A popular starting point: your stock % = 110 minus your age. At 25? About 85% stocks. At 60? About 50% stocks. It\'s not perfect — it\'s just a starting point to adjust from based on your personal comfort with risk.' },
    ],
    concept: 'A portfolio is your full collection of investments. Diversification spreads risk across assets that don\'t move in sync. Correlation measures how assets move together — low correlation = better diversification.',
    quiz: [
      { q: 'You invest $1000: $500 in Tech stocks, $300 in Gold, $200 in Bonds. Tech crashes -50%. What\'s your loss?', opts: ['$250 loss', '$500 loss', '$1000 loss', '$150 loss'], ans: 0, exp: '$500 × 50% = $250 loss. The other $500 (gold + bonds) is unaffected. Diversification limited your damage to 25% of portfolio vs 50%.' },
      { q: 'What does "asset allocation" mean?', opts: ['How you divide your money across different asset types', 'Buying only one type of asset', 'The total value of your investments', 'A type of stock order'], ans: 0, exp: 'Asset allocation is the strategic decision of how to divide your portfolio among asset classes (stocks, bonds, real estate, cash) based on your goals and risk tolerance.' }
    ]
  },
  {
    id: 'volatility', num: 11, icon: '🌊', title: 'Volatility',
    tag: 'The measure of market drama',
    scene: '📉📈🎢',
    dialogues: [
      { who: 'narrator', text: 'Alex is looking at two stocks on the FinCity big screen. One is a flat, calm line. The other is a wild roller coaster. Both ended the year at the same price — but the journey was completely different.' },
      { who: 'finn', text: 'Quick question: which job is riskier — one that pays exactly $3,000 every month, or one that pays anywhere between $0 and $10,000 randomly each month?' },
      { who: 'alex', text: 'The random one — even if the average might be higher, I can\'t plan around it.' },
      { who: 'finn', text: 'That unpredictability IS volatility. In investing, VOLATILITY measures how much an asset\'s price MOVES up and down over time. A stock that swings 10% every day is highly volatile. One that barely budges is low volatility.' },
      { who: 'alex', text: 'How is volatility actually measured with a number?' },
      { who: 'finn', text: 'Mathematically, it\'s the STANDARD DEVIATION of price changes — a measure of how far prices typically stray from their average. A 2% standard deviation means most days it moves about 2%. A 15% standard deviation means wild daily swings are normal.' },
      { who: 'alex', text: 'So volatile stocks are always bad investments?' },
      { who: 'finn', text: 'Not at all! Volatility is a double-edged sword. A stock that can fall 40% in a month can ALSO rise 40% in a month. High volatility = bigger risk AND bigger potential reward. Low volatility = steadier, predictable, but lower upside. Neither is "bad" — it depends on your goals.' },
      { who: 'alex', text: 'What types of stocks are typically volatile?' },
      { who: 'finn', text: 'Small companies, tech startups, biotech, cryptocurrency — anything where the future is highly uncertain. Stable businesses like supermarkets or electricity utilities have low volatility because their earnings are predictable. Nobody suddenly stops buying groceries.' },
      { who: 'alex', text: 'What is the VIX? I keep hearing about it.' },
      { who: 'finn', text: 'The VIX is the "Fear Index" — it measures EXPECTED volatility for the entire US stock market over the next 30 days. When investors are calm, VIX is low (around 15–20). When markets are panicking, VIX spikes. During COVID in March 2020, it hit 80. Extreme fear.' },
      { who: 'alex', text: 'Can I use the VIX to make smarter investment decisions?' },
      { who: 'finn', text: 'Yes! A very high VIX often signals a buying opportunity — stocks are cheap because people are panicking. A very low VIX can signal dangerous complacency before a correction. Savvy investors watch it as a market "temperature gauge." Some even trade the VIX itself as a volatility bet!' },
    ],
    concept: 'Volatility measures how much an asset\'s price swings. High volatility = big gains OR big losses. Low volatility = steady, predictable. VIX is the market\'s "fear gauge." Risk-averse investors prefer low volatility assets.',
    quiz: [
      { q: 'Stock A swings ±2% per day. Stock B swings ±15% per day. Which is more volatile?', opts: ['Stock B', 'Stock A', 'They are equal', 'Cannot tell from this data'], ans: 0, exp: 'Stock B with ±15% daily swings has much higher volatility. It offers bigger potential gains but also far greater risk of loss.' },
      { q: 'The VIX index spikes from 18 to 65. What does this likely indicate?', opts: ['Markets are panicking or crashing', 'Markets are hitting all-time highs', 'Interest rates were lowered', 'A major company went public'], ans: 0, exp: 'A VIX spike to 65 signals extreme fear and uncertainty in markets. This typically coincides with crashes or major crises — investors are expecting huge price swings.' }
    ]
  },
  {
    id: 'arbitrage', num: 12, icon: '⚖️', title: 'Arbitrage',
    tag: 'Risk-free profit from price differences',
    scene: '⚖️💡🔄',
    dialogues: [
      { who: 'narrator', text: 'Finn pulls Alex aside in the trading hall and whispers: "I\'ve spotted something. The same banana is selling for $1 at one stall and $1.20 at the stall next door. What would you do?"' },
      { who: 'alex', text: 'Buy from the cheap stall and sell to people at the expensive one? That\'s free money!' },
      { who: 'finn', text: 'You just discovered ARBITRAGE — exploiting a price difference for the same asset in different markets to earn a risk-free profit. Buy low here, sell high there, pocket the difference with no risk. In theory, it\'s the closest thing to a free lunch in finance.' },
      { who: 'alex', text: 'If it\'s risk-free, why doesn\'t everyone do it all the time?' },
      { who: 'finn', text: 'They do — and that\'s exactly why true arbitrage disappears almost instantly. The moment you start buying from the cheap market, demand there pushes prices up. Selling into the expensive market pushes prices down. Within seconds, the gap closes. Modern algorithmic traders scan every exchange simultaneously and exploit arbs in microseconds.' },
      { who: 'alex', text: 'What are some real examples of arbitrage?' },
      { who: 'finn', text: 'EXCHANGE ARBITRAGE: the same stock trading at slightly different prices on NYSE vs NASDAQ. Buy on one, sell on the other. MERGER ARBITRAGE: a company is being acquired at $50/share, but currently trades at $48 — buy it to capture the $2 gap. TRIANGULAR FX ARBITRAGE: exploiting inconsistencies between three currency pairs.' },
      { who: 'alex', text: 'How does triangular forex arbitrage work?' },
      { who: 'finn', text: 'If USD→EUR→GBP→USD doesn\'t equal exactly 1, you can profit cycling through three currencies. Example: Start with $100 → convert to €90 → convert to £80 → convert back to $102. A $2 profit from pure currency math. In practice these gaps are fractions of a pip and only worth it at massive scale.' },
      { who: 'alex', text: 'What is the "Law of One Price"?' },
      { who: 'finn', text: 'The LAW OF ONE PRICE states that in efficient markets, identical assets must have the same price everywhere. Arbitrage is the ENFORCEMENT MECHANISM — whenever prices diverge, arbitrageurs immediately trade to close the gap, restoring price equality. Arbitrage keeps markets honest and prices consistent globally.' },
      { who: 'alex', text: 'Are there slower types of arbitrage that don\'t require lightning-fast computers?' },
      { who: 'finn', text: 'Yes — STATISTICAL ARBITRAGE. Instead of identical assets, you look for historically correlated assets that have temporarily diverged. Coke and Pepsi stocks usually move together. If Coke drops 5% while Pepsi stays flat, a stat arb trader might buy Coke expecting it to revert. It\'s riskier (correlation can break!) but more accessible.' },
      { who: 'alex', text: 'So pure arbitrage is essentially gone from markets, but stat arb still works?' },
      { who: 'finn', text: 'Pure arb is extremely rare and fleeting — grab it in milliseconds or it\'s gone. Statistical arb persists because it requires judgment, patience, and risk tolerance that algorithms can\'t fully automate. Hedge funds like Renaissance Technologies have made billions from sophisticated stat arb strategies. The "free lunch" is rare — but not entirely extinct.' },
      { who: 'narrator', text: 'Arbitrage is the self-healing mechanism of financial markets. Every time prices diverge, arbitrageurs instantly correct them. Understanding arbitrage explains WHY markets stay efficient — and WHY the same asset can\'t sustainably trade at two different prices simultaneously.' },
    ],
    concept: 'Arbitrage = exploiting price differences for risk-free profit. Law of One Price: identical assets must trade at the same price. Pure arbitrage disappears instantly in modern markets. Statistical arbitrage exploits historical correlations that temporarily diverge.',
    quiz: [
      { q: 'BananaCo stock trades at $100 on Exchange A and $100.50 on Exchange B. A trader buys on A and sells on B. What is this?', opts: ['Pure arbitrage — risk-free $0.50 profit per share', 'Speculation — risky bet on price direction', 'Market making — providing liquidity', 'Hedging — reducing risk'], ans: 0, exp: 'Buying at $100 and immediately selling at $100.50 for the same asset in different markets is textbook arbitrage — a risk-free profit. In practice, this gap would close within milliseconds.' },
      { q: 'The "Law of One Price" says that:', opts: ['Identical assets must trade at the same price in efficient markets', 'All stocks eventually reach the same price', 'Only one buyer can set the market price', 'Prices can only move in one direction'], ans: 0, exp: 'The Law of One Price is enforced by arbitrage: whenever the same asset trades at different prices, traders immediately buy the cheaper and sell the dearer, closing the gap.' }
    ]
  },
  {
    id: 'interest-rates', num: 13, icon: '🏛️', title: 'Interest Rates Market',
    tag: 'The price of borrowing money',
    scene: '🏦💵🔢',
    dialogues: [
      { who: 'narrator', text: 'Alex needs $5,000 to expand their FinCity fruit stand. They walk into FinCity National Bank, where Finn explains how borrowing money really works.' },
      { who: 'finn', text: 'Let\'s start from scratch. When you borrow money, you\'re essentially RENTING it. Just like renting a car costs money per day, borrowing money costs money per year. That fee is called INTEREST.' },
      { who: 'alex', text: 'So if I borrow $5,000, I pay back MORE than $5,000?' },
      { who: 'finn', text: 'Exactly. The INTEREST RATE is that extra cost, expressed as a percentage per year. Borrow $5,000 at 10% annual interest — you owe $500 in interest after one year, plus the original $5,000 back. The lender earns $500 for letting you use their money.' },
      { who: 'alex', text: 'Who decides what the interest rate is?' },
      { who: 'finn', text: 'For the whole economy, it\'s the CENTRAL BANK — like the US Federal Reserve, the European Central Bank, or the Bank of England. They set a base rate, and all commercial banks adjust their rates from there. This base rate is one of the most powerful levers in the entire global economy.' },
      { who: 'alex', text: 'Why would a central bank raise or lower this rate?' },
      { who: 'finn', text: 'To control the economy! HIGH rates = expensive borrowing = people and businesses borrow less = less spending = prices stop rising (inflation cools). LOW rates = cheap borrowing = more spending and investment = economy grows. It\'s like the economy\'s thermostat.' },
      { who: 'alex', text: 'What\'s the difference between simple and compound interest?' },
      { who: 'finn', text: 'SIMPLE INTEREST is calculated only on the original amount. COMPOUND INTEREST is interest on your interest too! Example: $1,000 at 10% for 2 years. Simple: $1,200. Compound: Year 1 → $1,100, Year 2 → $1,100 × 1.10 = $1,210. That extra $10 is "interest on interest."' },
      { who: 'alex', text: 'That\'s only a $10 difference — not that impressive?' },
      { who: 'finn', text: 'Give it 30 years! $1,000 at 10% compounded = $17,449. Simple interest gives just $4,000. The longer you wait, the more dramatic the gap becomes. Einstein supposedly called compound interest "the eighth wonder of the world" — and he wasn\'t wrong.' },
      { who: 'alex', text: 'How do interest rate changes affect stocks and investments?' },
      { who: 'finn', text: 'When rates RISE, bond prices FALL (new bonds pay more, making old ones less attractive) and stocks often fall too (companies pay more to borrow, hurting profits). When rates FALL, both tend to rise. This is why every word from the Fed chairman is watched obsessively by investors worldwide.' },
    ],
    concept: 'Interest rate = cost of borrowing money. Central banks raise rates to fight inflation, cut rates to stimulate growth. Compound interest = earning interest on your interest. Bonds are priced on interest rates — rates up, bond prices down.',
    quiz: [
      { q: 'You invest $1,000 at 8% annual compound interest. After 2 years, how much do you have?', opts: ['$1,166.40', '$1,160', '$1,080', '$1,200'], ans: 0, exp: 'Year 1: $1000 × 1.08 = $1,080. Year 2: $1,080 × 1.08 = $1,166.40. That extra $6.40 is the "interest on interest" — the magic of compounding!' },
      { q: 'When the central bank RAISES interest rates, what typically happens to the economy?', opts: ['Borrowing slows, inflation cools', 'Borrowing surges, economy booms', 'Stock market always rises', 'Currency always weakens'], ans: 0, exp: 'Higher rates make loans more expensive for businesses and consumers, reducing spending and investment. This cools down an overheating economy and brings inflation down.' }
    ]
  },
  {
    id: 'fx-market', num: 14, icon: '🌍', title: 'FX Market',
    tag: 'Trading one currency for another',
    scene: '✈️💴💶💵',
    dialogues: [
      { who: 'narrator', text: 'Alex is at the FinCity airport, about to fly to EuroLand. They need to exchange their US dollars for Euros. Finn explains why this is far more fascinating than it looks.' },
      { who: 'finn', text: 'Let\'s start with a basic question: why do different currencies even exist? Why can\'t everyone just use one global currency?' },
      { who: 'alex', text: 'I guess because each country controls its own money and economy?' },
      { who: 'finn', text: 'Exactly. Each country (or currency zone) issues its own currency and controls its supply. The FOREIGN EXCHANGE market — called FOREX or FX — is where these currencies are traded against each other, 24 hours a day, 7 days a week, nonstop.' },
      { who: 'alex', text: 'How big is this market actually?' },
      { who: 'finn', text: '$7 TRILLION traded every single day. That\'s bigger than ALL the world\'s stock markets combined. It\'s the largest financial market on Earth. Banks, corporations, governments, hedge funds, tourists — everyone participates.' },
      { who: 'alex', text: 'How is an exchange rate determined? Why is $1 worth 0.92 euros today and not some other number?' },
      { who: 'finn', text: 'Pure SUPPLY AND DEMAND. If the US economy is booming and global investors want to buy US assets, they need dollars — demand rises, dollar price rises. If the US has high inflation, the dollar buys less, its value falls. Economic strength, interest rates, and politics all constantly move currency prices.' },
      { who: 'alex', text: 'How do I read a currency rate? Like EUR/USD = 1.10 — what exactly does that mean?' },
      { who: 'finn', text: 'Currency pairs always show how much of the SECOND currency you get for ONE unit of the FIRST. EUR/USD = 1.10 means: 1 Euro buys 1.10 US Dollars. EUR is the BASE currency. USD is the QUOTE currency. Easy memory trick: "one of the first buys X of the second."' },
      { who: 'alex', text: 'So if EUR/USD goes from 1.10 to 1.20, the Euro got stronger against the dollar?' },
      { who: 'finn', text: 'Yes! Each Euro now buys MORE dollars — the Euro strengthened. A falling EUR/USD means the Euro weakened. Forex traders profit by correctly predicting these movements, sometimes holding positions for just seconds!' },
      { who: 'alex', text: 'How do big companies deal with currency risk — like Apple earning in Euros but reporting in dollars?' },
      { who: 'finn', text: 'Great question! That\'s currency risk. If Apple earns €100M and the euro weakens vs the dollar, those euros convert to fewer dollars when reported. Companies HEDGE this using FX forward contracts — locking in today\'s exchange rate for future payments. We\'ll cover hedging in detail soon!' },
    ],
    concept: 'Forex (FX) is the global market for trading currencies. Exchange rates are currency pair prices. Major pairs: EUR/USD, GBP/USD, USD/JPY. Rates shift based on interest rates, inflation, GDP, and political events.',
    quiz: [
      { q: 'EUR/USD = 1.10. You convert $1,100 USD to EUR. How many euros do you get?', opts: ['€1,000', '€1,100', '€1,210', '€910'], ans: 0, exp: 'EUR/USD = 1.10 means $1.10 buys €1. So $1,100 ÷ 1.10 = €1,000. You always divide by the rate to get the base currency.' },
      { q: 'Country A raises interest rates to 6% while Country B stays at 2%. What likely happens to Country A\'s currency?', opts: ['It strengthens — more investors buy it for higher yield', 'It weakens — borrowing is expensive', 'No effect on currency', 'It becomes fixed permanently'], ans: 0, exp: 'Higher interest rates attract foreign investors seeking better returns. They buy Country A\'s currency to invest there, increasing demand and strengthening it.' }
    ]
  },
  {
    id: 'commodities', num: 15, icon: '⛽', title: 'Commodity & Energy Markets',
    tag: 'Trading real physical things',
    scene: '🛢️🌽🥇🌤️',
    dialogues: [
      { who: 'narrator', text: 'Alex discovers FinCity\'s massive warehouse district — rows of storage filled with gold bars, oil drums, sacks of wheat, and bags of coffee. This is where the world\'s raw materials get priced.' },
      { who: 'finn', text: 'Everything you own started as a RAW MATERIAL. Your phone contains copper and rare earth metals. Your bread came from wheat. Your car runs on oil. These raw materials — called COMMODITIES — are traded on global markets just like stocks.' },
      { who: 'alex', text: 'What exactly counts as a commodity?' },
      { who: 'finn', text: 'Any raw material that\'s interchangeable — one barrel of West Texas crude oil is essentially the same as any other barrel. Commodities fall into four groups: ENERGY (oil, natural gas), METALS (gold, silver, copper), AGRICULTURE (wheat, corn, coffee, soybeans), and LIVESTOCK (cattle, pork).' },
      { who: 'alex', text: 'Why do oil prices affect EVERYTHING? I hear about it constantly.' },
      { who: 'finn', text: 'Because oil is in almost EVERYTHING. It fuels the trucks that deliver food. It heats homes. Plastics come from oil. When oil prices rise, costs increase for nearly every product and service. Higher oil = higher inflation across the whole economy. That\'s why governments and central banks obsess over it.' },
      { who: 'alex', text: 'What drives commodity prices up and down?' },
      { who: 'finn', text: 'Purely SUPPLY AND DEMAND. A drought destroys wheat crops → supply drops → wheat price spikes. OPEC (the oil cartel) cuts production → less oil available → oil price rises. A global recession → factories slow down → they need less copper → copper price falls. It\'s that direct.' },
      { who: 'alex', text: 'Does a trader actually take delivery of 1,000 barrels of oil?' },
      { who: 'finn', text: 'Ha! Most commodity traders NEVER see the actual stuff. They trade FUTURES CONTRACTS — agreements to buy or sell a set amount at a future date. Airlines buy oil futures to lock in fuel costs. Farmers sell wheat futures to guarantee a crop price before harvest. Speculators trade purely for profit.' },
      { who: 'alex', text: 'I\'ve heard gold is a "safe haven." What does that actually mean?' },
      { who: 'finn', text: 'When stock markets crash or inflation spikes, investors flee to gold. It\'s been valued for 5,000 years, can\'t be printed like paper money, and isn\'t tied to any single country. In times of fear, gold tends to HOLD its value when everything else falls. It\'s the ultimate financial security blanket.' },
      { who: 'alex', text: 'Can I invest in commodities without literally storing oil in my garage?' },
      { who: 'finn', text: 'Absolutely! Commodity ETFs (Exchange-Traded Funds) let you buy a fund that tracks oil, gold, or agricultural prices. Or invest in companies that PRODUCE commodities — oil companies, gold miners, farming conglomerates. Much more practical than physical storage!' },
    ],
    concept: 'Commodities are raw materials: energy (oil, gas), metals (gold, silver, copper), agriculture (wheat, corn, coffee). Prices follow supply/demand. Commodities can hedge inflation since their prices tend to rise when inflation rises.',
    quiz: [
      { q: 'OPEC (oil cartel) unexpectedly CUTS oil production by 20%. What likely happens to oil prices?', opts: ['Prices rise — less supply', 'Prices fall — less supply', 'No change', 'Prices fall — more demand'], ans: 0, exp: 'Basic supply/demand: less supply with the same demand = higher prices. OPEC production cuts are specifically used to push oil prices up to benefit member countries.' },
      { q: 'Why do investors sometimes buy gold when the economy is uncertain?', opts: ['Gold is a "safe haven" — holds value when stocks crash', 'Gold always pays dividends', 'Gold never loses value', 'It is required by law'], ans: 0, exp: 'Gold is considered a safe haven asset. When stocks crash or inflation rises, investors flee to gold as it tends to hold its value and isn\'t tied to any single economy or currency.' }
    ]
  },
  {
    id: 'derivatives', num: 16, icon: '📜', title: 'Derivatives',
    tag: 'Contracts derived from other assets',
    scene: '📜🔗🍌📊',
    dialogues: [
      { who: 'narrator', text: 'Finn leads Alex to the most complex corner of FinCity: The Derivatives District. The buildings look familiar — but everything here is a layer ABOVE the actual assets.' },
      { who: 'finn', text: 'Let\'s start with a real-world situation. You\'re planning a wedding in 6 months. The florist says roses cost $5 today — but prices fluctuate. You sign a contract guaranteeing $5 per rose in 6 months, no matter what happens to prices.' },
      { who: 'alex', text: 'That\'s like insurance against price changes.' },
      { who: 'finn', text: 'Exactly! And that\'s the core of a DERIVATIVE — a financial CONTRACT whose value is DERIVED FROM something else (the UNDERLYING ASSET). That underlying could be a stock, oil price, currency, interest rate, or even weather. The derivative itself has no value on its own.' },
      { who: 'alex', text: 'So a derivative isn\'t an asset itself — it\'s a contract ABOUT an asset?' },
      { who: 'finn', text: 'Right. There are four main types: FUTURES (you MUST buy/sell on a future date at today\'s agreed price), OPTIONS (you have the RIGHT but not the obligation — covered next chapter), SWAPS (exchange one stream of payments for another), and FORWARDS (custom futures negotiated directly between two parties).' },
      { who: 'alex', text: 'Give me a real futures example?' },
      { who: 'finn', text: 'You\'re a baker. Wheat is $300/ton today and you need 10 tons in 6 months. You sign a FUTURES CONTRACT: you agree to buy 10 tons at $300 in 6 months, no matter what the market price is then. Wheat spikes to $400? You still pay $300. You\'ve LOCKED IN your cost — you\'ve HEDGED.' },
      { who: 'alex', text: 'What if wheat DROPS to $200? Am I stuck paying $300?' },
      { who: 'finn', text: 'Yes — that\'s the downside of futures. It\'s an OBLIGATION, not a choice. You must transact at the agreed price even if the market moved against you. This is why OPTIONS are often preferred — they give you the right WITHOUT the obligation.' },
      { who: 'alex', text: 'I\'ve heard derivatives are extremely risky. Why?' },
      { who: 'finn', text: 'LEVERAGE. Derivatives let you control a large position with a small deposit. Put $10,000 down to control $100,000 of oil futures — that\'s 10x leverage. If oil moves 5% in your favor, you gain $5,000 on a $10,000 deposit — 50% return. But if oil moves 5% against you, you LOSE $5,000. Half your money, gone.' },
      { who: 'alex', text: 'Is this what caused the 2008 financial crisis?' },
      { who: 'finn', text: 'Partly! Banks created complex mortgage-backed derivatives called CDOs. They were sold with massive leverage, with no one fully understanding the risk. When US house prices fell, the entire chain of derivatives collapsed. Derivatives are powerful tools for managing risk — but used recklessly, they can bring down the entire financial system.' },
    ],
    concept: 'Derivatives are contracts that derive value from an underlying asset. Key types: Futures (obligation), Options (right, not obligation), Swaps (exchange cash flows). They enable hedging, speculation, and arbitrage. Leverage amplifies both gains and losses.',
    quiz: [
      { q: 'A baker buys a wheat FUTURES contract at $300/ton for delivery in 6 months. Wheat rises to $400/ton. What does the baker gain?', opts: ['$100/ton saved on their wheat costs', '$400/ton saved', 'Nothing — futures only help sellers', 'They lose $100/ton'], ans: 0, exp: 'The baker locked in $300/ton. Market price rose to $400. They effectively "saved" $100/ton vs buying at market. They can now buy at their contracted $300 price.' },
      { q: 'Which best describes a "derivative"?', opts: ['A contract whose value depends on an underlying asset', 'A stock that pays dividends', 'A savings account', 'A type of bank loan'], ans: 0, exp: 'Derivatives get their value FROM something else (the underlying asset). On their own, they have no intrinsic value — only the value tied to what they reference.' }
    ]
  },
  {
    id: 'options-basics', num: 17, icon: '📋', title: 'Options: The Basics',
    tag: 'What makes an option valuable',
    scene: '📋🎯💡',
    dialogues: [
      { who: 'narrator', text: 'Alex has heard "options" mentioned throughout FinCity. Before diving into the Options Exchange, Finn explains exactly what gives an option its value from first principles.' },
      { who: 'finn', text: 'You understand that an option is the right — not obligation — to buy or sell something at a fixed price. But WHY does that right have value? Let\'s build intuition from scratch.' },
      { who: 'alex', text: 'I guess the right to buy something cheap has value if the market price is higher?' },
      { who: 'finn', text: 'Exactly — that\'s called INTRINSIC VALUE. For a CALL option with a $50 strike, if the stock is at $60, you can buy at $50 and instantly "sell" at $60 — a $10 gain. Intrinsic value = MAX(stock price − strike price, 0). If the stock is below the strike, intrinsic value is zero — it can\'t be negative.' },
      { who: 'alex', text: 'So intrinsic value is the "right now" value if I exercised immediately?' },
      { who: 'finn', text: 'Exactly. But options almost always cost MORE than their intrinsic value alone. The extra amount is TIME VALUE. Even if an out-of-the-money option has zero intrinsic value today, the stock MIGHT move above the strike before expiry. That possibility has value — you\'re paying for potential.' },
      { who: 'alex', text: 'What determines how much time value an option has?' },
      { who: 'finn', text: 'Five factors: SPOT PRICE (current stock price), STRIKE PRICE (your locked-in price), TIME TO EXPIRY (more time = more chance of movement = more time value), VOLATILITY (higher vol = larger potential swings = more chance of profit = higher option price), and RISK-FREE RATE.' },
      { who: 'alex', text: 'Why does higher volatility make options more expensive? That seems counterintuitive.' },
      { who: 'finn', text: 'Think about it this way: if a stock NEVER moves, a call option is worthless — the stock won\'t rise above the strike. But if the stock could swing 50% in either direction, there\'s a real chance it ends up deep in-the-money. Options only benefit from upside moves, and your loss is capped at the premium. So high vol = more upside potential with the same capped downside.' },
      { who: 'alex', text: 'What is Delta? I keep seeing it mentioned.' },
      { who: 'finn', text: 'DELTA measures how much the option price moves when the stock price moves $1. A delta of 0.5 means: stock rises $1 → option rises $0.50. Deep in-the-money calls have delta near 1.0 (move almost like the stock). Far out-of-the-money options have delta near 0 (barely respond to small moves). Delta is also the approximate probability the option expires in-the-money.' },
      { who: 'alex', text: 'What happens to time value as expiry approaches?' },
      { who: 'finn', text: 'It DECAYS. Every day that passes, there\'s less time for the stock to move. This decay accelerates as expiry approaches — called THETA decay. Option sellers LOVE theta decay (time works for them). Option buyers race against it. An option you bought for $5 with 3 months left might only be worth $1 with 1 week left, even if the stock hasn\'t moved.' },
      { who: 'alex', text: 'So buying options is risky because time keeps eroding their value?' },
      { who: 'finn', text: 'Yes — and this is why most retail traders who "just buy options" lose money. You need the stock to move FAST and FAR enough in the right direction to overcome time decay. Professionals often SELL options to collect premium, letting time work in their favour. Options are powerful — but they require understanding all five pricing factors to use wisely.' },
      { who: 'narrator', text: 'Option price = Intrinsic Value + Time Value. The five inputs to any option price are: spot price, strike price, time to expiry, volatility, and interest rates. Understanding these building blocks is the gateway to the entire world of options strategy.' },
    ],
    concept: 'Option price = Intrinsic Value + Time Value. Intrinsic = max(S−K, 0) for calls. Time value reflects probability of future price moves. Volatility increases option prices. Theta decay erodes time value daily. Delta = sensitivity to stock price moves.',
    quiz: [
      { q: 'A call option has a strike of $80. The stock is at $95. What is the intrinsic value?', opts: ['$15', '$80', '$95', '$0'], ans: 0, exp: 'Intrinsic value for a call = max(Stock price − Strike price, 0) = max($95 − $80, 0) = $15. This is the immediate profit if you exercised right now.' },
      { q: 'Volatility on BananaCo rises from 20% to 45%. What happens to the price of its options?', opts: ['They become more expensive', 'They become cheaper', 'No effect on option price', 'Only put options are affected'], ans: 0, exp: 'Higher volatility means larger potential price swings — creating more chance the option ends up deep in-the-money. Since option holders benefit from big moves but have capped downside, higher vol always increases option prices (both calls and puts).' }
    ]
  },
  {
    id: 'options', num: 18, icon: '🎯', title: 'Options Exchanges',
    tag: 'The right, but not the obligation',
    scene: '🎯📋🏷️',
    dialogues: [
      { who: 'narrator', text: 'Alex enters the FinCity Options Exchange — the most sophisticated trading venue in all of FinCity. Here, traders don\'t just buy assets — they buy and sell the RIGHT to buy or sell.' },
      { who: 'finn', text: 'Let\'s start with an everyday example. You find a house you love. You pay the owner $500 for the RIGHT to buy it for $200,000 any time in the next 3 months. The owner agrees. You haven\'t bought the house — just the option to buy it.' },
      { who: 'alex', text: 'So I\'ve locked in the purchase price but haven\'t fully committed yet?' },
      { who: 'finn', text: 'Exactly! That $500 is the PREMIUM — what you paid for the option. $200,000 is the STRIKE PRICE — your locked-in purchase price. 3 months is the EXPIRY — your deadline. That\'s a CALL OPTION: the right to BUY at the strike price.' },
      { who: 'alex', text: 'What makes this useful? Why not just buy the house outright?' },
      { who: 'finn', text: 'Flexibility and leverage! If prices rise to $230,000, you exercise your option — buy at $200,000, instantly worth $230,000. Profit: $30,000 from a $500 bet. Without the option, you\'d need the full $200,000 upfront. Options let you control large assets cheaply.' },
      { who: 'alex', text: 'What if the house price falls to $180,000? I wouldn\'t want to buy at $200,000 anymore.' },
      { who: 'finn', text: 'Then you simply walk away — let the option expire. Your MAXIMUM LOSS is only the $500 premium you paid. That\'s the key advantage over buying outright: your downside is CAPPED at the premium. You\'re never forced to buy at a bad price.' },
      { who: 'alex', text: 'You mentioned CALL options. What\'s a PUT option?' },
      { who: 'finn', text: 'A PUT option is the right to SELL at the strike price. Say you already own the house and worry prices might crash. Buy a PUT at $200,000 — if prices fall to $150,000, you can still force someone to buy it at your $200,000 strike. It\'s downside protection.' },
      { who: 'alex', text: 'So calls profit when prices RISE, puts profit when prices FALL?' },
      { who: 'finn', text: 'Exactly! Long CALL = bullish bet (expecting price to rise). Long PUT = bearish bet (expecting price to fall). They\'re used for speculation — but also for PROTECTION. A PUT on shares you already own is essentially portfolio insurance.' },
      { who: 'alex', text: 'What does "in the money" mean?' },
      { who: 'finn', text: 'A CALL is "in the money" (ITM) when the current price is ABOVE the strike — exercising it RIGHT NOW would be profitable. A PUT is ITM when the price is BELOW the strike. "Out of the money" (OTM) means exercising isn\'t worth it yet. Knowing your option\'s status tells you whether to exercise, hold, or let it expire.' },
    ],
    concept: 'Call Option: right to BUY at strike price. Put Option: right to SELL at strike price. Premium: cost of the option. In-the-money: exercising is profitable. Out-of-the-money: exercising isn\'t worth it yet. Options expire on a set date.',
    quiz: [
      { q: 'You buy a CALL option on BananaCo: Strike $55, Premium $3, Current price $50. Stock jumps to $65. What\'s your profit per share?', opts: ['$7', '$10', '$65', '$3'], ans: 0, exp: 'You exercise the right to buy at $55. You can immediately sell at $65. Profit = $65 − $55 − $3 premium = $7 per share.' },
      { q: 'A PUT option gives you the right to ____?', opts: ['Sell a stock at the strike price', 'Buy a stock at the strike price', 'Receive dividends automatically', 'Borrow the stock'], ans: 0, exp: 'A PUT = right to SELL at the strike price. Profitable when the stock price falls BELOW the strike price. Used for speculation or protection (hedging).' }
    ]
  },
  {
    id: 'put-call-parity', num: 19, icon: '🔄', title: 'Put-Call Parity',
    tag: 'The iron law connecting calls and puts',
    scene: '🔄⚖️📐',
    dialogues: [
      { who: 'narrator', text: 'Finn leads Alex to a whiteboard in the Options Exchange. "There\'s a mathematical law," Finn says, "that links the price of calls and puts. Violate it and money can be printed from thin air."' },
      { who: 'finn', text: 'You now know what calls and puts are. Here\'s a question: if I gave you a CALL option (right to buy at $100) and enough cash to pay the strike ($100 invested risk-free), what have I effectively given you?' },
      { who: 'alex', text: 'Umm... at expiry, if the stock is above $100, I\'d exercise the call and own the stock. If it\'s below $100, I just take the cash back. So... it\'s kind of like owning the stock but with a floor at $100?' },
      { who: 'finn', text: 'Exactly! Call + Cash = owning the stock with downside protection. Now here\'s the key: what if instead I gave you the STOCK itself PLUS a PUT option (right to sell at $100)?' },
      { who: 'alex', text: 'If the stock goes above $100, I keep the gains from the stock. If it falls below $100, I exercise the put and sell at $100. So... same payoff! Both strategies end up the same at expiry?' },
      { who: 'finn', text: 'You\'ve just proved PUT-CALL PARITY! Because both portfolios produce identical payoffs at expiry, they must cost exactly the same today. Written as an equation: C + PV(K) = S + P. Or rearranged: C − P = S − PV(K). Where C = call price, P = put price, S = stock price, PV(K) = present value of strike.' },
      { who: 'alex', text: 'What does PV(K) mean exactly?' },
      { who: 'finn', text: 'PV(K) is the PRESENT VALUE of the strike price — how much you need to invest TODAY at the risk-free rate to have exactly $K (the strike) at expiry. If the strike is $100, expiry is 1 year, and risk-free rate is 5%, PV(K) = $100 ÷ 1.05 ≈ $95.24.' },
      { who: 'alex', text: 'Let me try a real example. Call = $8, Put = $3, Stock = $100, Strike = $98, PV(K) = $95. Does parity hold?' },
      { who: 'finn', text: 'Left side: C − P = $8 − $3 = $5. Right side: S − PV(K) = $100 − $95 = $5. They match — parity holds! No arbitrage is possible.' },
      { who: 'alex', text: 'What if parity is violated? Say the call is $10 instead of $8?' },
      { who: 'finn', text: 'Then C − P = $10 − $3 = $7, but S − PV(K) = $5. The left side is $2 too expensive. An arbitrageur would SELL the call, BUY the put, BUY the stock, and BORROW PV(K). The combined position earns a risk-free $2 profit per share. They\'d do this in massive size until the prices adjust and parity is restored.' },
      { who: 'alex', text: 'So parity is maintained because any violation gets instantly arbitraged away?' },
      { who: 'finn', text: 'Exactly. Put-call parity is enforced by arbitrage — the market\'s immune system. It\'s also enormously useful practically: if you know three of the four values (call, put, stock, strike), you can calculate the fourth. And it allows you to CREATE synthetic positions — e.g., a synthetic long call = long stock + long put.' },
      { who: 'narrator', text: 'Put-call parity is one of the fundamental no-arbitrage relationships in finance. It was formalized by Hans Stoll in 1969 and forms the backbone of all options pricing theory. Any options trader who ignores it is leaving free money on the table — or risking being arbitraged against.' },
    ],
    concept: 'Put-Call Parity: C − P = S − PV(K). A call plus cash equals a stock plus a put (both give same payoff). Violation creates risk-free arbitrage. Used to price synthetic positions. Foundation of all options pricing theory.',
    quiz: [
      { q: 'C = $6, S = $100, PV(K) = $97. Using put-call parity C − P = S − PV(K), what should the put price P be?', opts: ['$3', '$6', '$97', '$9'], ans: 0, exp: 'C − P = S − PV(K) → $6 − P = $100 − $97 = $3 → P = $6 − $3 = $3. If the put traded at any other price, arbitrage would be possible.' },
      { q: 'Put-call parity is ultimately maintained by:', opts: ['Arbitrage — traders immediately exploit any violation for risk-free profit', 'Government regulation of options prices', 'Market makers agreeing to keep prices equal', 'The exchange setting call and put prices daily'], ans: 0, exp: 'Any violation of parity creates a risk-free profit. Arbitrageurs immediately trade to capture it, which restores the relationship. Parity holds because violations are instantly and aggressively exploited.' }
    ]
  },
  {
    id: 'payoffs', num: 20, icon: '📐', title: 'Payoffs',
    tag: 'Mapping your profit and loss',
    scene: '📐📊💹',
    dialogues: [
      { who: 'narrator', text: 'Finn pulls out a whiteboard. "Before you ever enter a trade," Finn says firmly, "you need to map out what you stand to GAIN — and LOSE — at every possible price. That\'s a payoff diagram."' },
      { who: 'finn', text: 'Every trade has a PAYOFF — your profit or loss depending on what the price does. Let\'s start with the simplest: you own a stock outright. What happens to your P&L?' },
      { who: 'alex', text: 'If it goes up I make money. If it goes down I lose money. Linear, right?' },
      { who: 'finn', text: 'Exactly! Buy BananaCo at $50. Stock hits $80? Profit = +$30. Falls to $20? Loss = −$30. Every $1 the stock moves = $1 gain or loss for you. And it can theoretically fall all the way to zero — unlimited loss.' },
      { who: 'alex', text: 'How does the payoff shape look different for a call option?' },
      { who: 'finn', text: 'Totally different! Call option: Strike $55, Premium $3. Below $55 at expiry → option expires worthless, you lose exactly $3 (the premium). Between $55–$58 → you start recovering losses. Above $58 (strike + premium) → profit. The shape has a FLAT FLOOR at −$3, then slopes upward.' },
      { who: 'alex', text: 'So the call option has a max loss of $3, but owning the stock directly risks losing $50 if it goes to zero?' },
      { who: 'finn', text: 'YES — and that\'s the huge advantage of buying options. Your risk is CAPPED at the premium you paid. You can never lose more than what you paid for the option. The trade-off is that you need the stock to move MORE to make a profit (above $58 rather than just above $50).' },
      { who: 'alex', text: 'What about a put option payoff?' },
      { who: 'finn', text: 'Mirror image! Put option: Strike $50, Premium $2. Above $50 → option worthless, lose $2. Below $50 → start recovering. Below $48 (strike − premium) → profit. The diagram slopes DOWNWARD as prices fall — you\'re making money on declining prices.' },
      { who: 'alex', text: 'How do I quickly calculate where I break even?' },
      { who: 'finn', text: 'Simple formulas: CALL break-even = Strike + Premium. PUT break-even = Strike − Premium. These are the exact prices the stock must reach for you to recover what you paid. Above break-even for calls: profit. Below break-even for puts: profit.' },
      { who: 'alex', text: 'Why do professional traders sketch payoff diagrams before every trade?' },
      { who: 'finn', text: 'Because it forces you to answer three questions BEFORE you commit: What\'s my maximum loss? Where do I break even? At what price do I profit? If you can\'t answer those, you don\'t understand your trade. Drawing the payoff literally is professional risk management 101 — never skip it.' },
    ],
    concept: 'Payoff = profit/loss at expiry. Long Stock: linear payoff. Long Call: lose premium if below strike, profit above (strike + premium). Long Put: lose premium above strike, profit below (strike − premium). Always know your break-even!',
    quiz: [
      { q: 'You buy a call option: strike $60, premium $4. At what stock price do you BREAK EVEN?', opts: ['$64', '$60', '$56', '$4'], ans: 0, exp: 'Call break-even = Strike + Premium = $60 + $4 = $64. Below $64 you lose money (up to max loss of $4 premium). Above $64 you profit.' },
      { q: 'What is the MAXIMUM LOSS when you BUY a call option?', opts: ['The premium you paid', 'The full stock price', 'Unlimited', 'The strike price'], ans: 0, exp: 'When you buy an option, your maximum loss is capped at the premium you paid. If the option expires worthless, you lose $0 beyond that premium — a key advantage over short-selling.' }
    ]
  },
  {
    id: 'hedging', num: 21, icon: '🛡️', title: 'Hedging',
    tag: 'Insurance for your investments',
    scene: '🛡️📉😌',
    dialogues: [
      { who: 'narrator', text: 'Alex owns 100 BananaCo shares at $50 each — a $5,000 investment. Bad news about a banana disease is spreading. Finn shows up with a solution.' },
      { who: 'finn', text: 'Let me ask you something. You insure your car, right? Even though you hope you never need it, you pay a premium every month so that if something goes wrong, you\'re covered financially. HEDGING is exactly the same idea — but for your investments.' },
      { who: 'alex', text: 'So it\'s buying insurance for my stocks?' },
      { who: 'finn', text: 'Precisely! HEDGING means taking a SECOND position that moves in the OPPOSITE direction to your main investment. If your main investment falls, the hedge rises to offset some of that loss. You don\'t make extra profit — you LIMIT your downside. You trade some potential gain for protection.' },
      { who: 'alex', text: 'How would I actually hedge my BananaCo shares?' },
      { who: 'finn', text: 'The simplest way: buy a PUT OPTION on BananaCo. Pay $2 per share for the right to SELL at $48 (the strike price) any time in the next 3 months. For 100 shares, that\'s $200 total — your insurance premium.' },
      { who: 'alex', text: 'What happens if the stock crashes to $30?' },
      { who: 'finn', text: 'Without hedge: your 100 shares are worth $3,000 instead of $5,000 — a $2,000 loss. WITH the hedge: you exercise your put, selling at $48. Revenue: $4,800 minus $200 premium cost. Net result: −$400 instead of −$2,000. The hedge SAVED you $1,600!' },
      { who: 'alex', text: 'What if the stock actually RISES to $70? Did I waste that $200 on the put?' },
      { who: 'finn', text: 'The put expires worthless — you lose the $200 premium. But your 100 shares are now worth $7,000 — a $2,000 profit! Net: +$1,800. Think of the $200 like a car insurance premium you never had to claim. You\'re still glad you had the protection.' },
      { who: 'alex', text: 'Who uses hedging in the real world outside of investing?' },
      { who: 'finn', text: 'Everyone who faces financial uncertainty! Airlines hedge fuel costs with oil futures — locking in prices months ahead. Apple hedges currency risk with FX contracts. Farmers sell wheat futures before harvest to lock in a guaranteed price. Hedging is how professionals manage uncertainty in business.' },
      { who: 'alex', text: 'Can you hedge too much? Is 100% hedging even possible?' },
      { who: 'finn', text: 'You can — and it\'s a mistake. If you hedge 100% of your portfolio, you eliminate all risk — but also all return potential. The art is hedging the RIGHT risks. Fund managers ask: which risks are we PAID to take (keep those), which risks are just noise (hedge those). Balance is everything.' },
    ],
    concept: 'Hedging reduces risk by taking an offsetting position. Common techniques: buy put options to protect long stock, use futures to lock in prices, use inverse ETFs. Hedging costs money (the premium/cost) but reduces downside risk.',
    quiz: [
      { q: 'You own stock at $100. To hedge, you buy a put option with strike $90 for $3 premium. The stock crashes to $60. What is your effective sell price?', opts: ['$87 ($90 − $3 premium)', '$90', '$60', '$97'], ans: 0, exp: 'You exercise the put and sell at $90 (the strike). Net of the $3 premium cost, your effective outcome is $87. Without the hedge, you\'d be stuck at $60 — a $27 improvement!' },
      { q: 'What is the primary purpose of hedging?', opts: ['To limit losses, even at the cost of some gains', 'To maximize profits', 'To avoid all risk completely', 'To trade more frequently'], ans: 0, exp: 'Hedging trades some potential upside for downside protection. It\'s not about eliminating risk entirely — that\'s impossible — but about managing it to an acceptable level.' }
    ]
  },
  {
    id: 'otc', num: 22, icon: '🤝', title: 'OTC Market',
    tag: 'Direct deals, no exchange needed',
    scene: '🤝🏢📋',
    dialogues: [
      { who: 'narrator', text: 'Alex has heard about a unique investment: a $1 million custom BananaCo bond with very specific terms. It\'s not listed on any exchange. Finn explains why — and how OTC markets work.' },
      { who: 'finn', text: 'You already understand stock exchanges — like the NYSE. Think of them like a supermarket: standardized products at posted prices, regulated, transparent, with a guarantee your trade will settle. But not everything fits in a supermarket.' },
      { who: 'alex', text: 'What doesn\'t fit in an exchange?' },
      { who: 'finn', text: 'Custom deals! What if you want a completely unique contract — specific amount, negotiated price, unusual terms? That\'s where OVER-THE-COUNTER (OTC) markets come in. Trades happen DIRECTLY between two parties. No exchange, no middleman, no standardized product.' },
      { who: 'alex', text: 'What kinds of things actually trade OTC?' },
      { who: 'finn', text: 'Lots! Most BONDS are traded OTC — corporations and governments negotiate directly with large investors. The entire FOREX market is OTC (no central exchange, just a network of banks). Complex DERIVATIVES like interest rate swaps. Even some small-company stocks. The global OTC derivatives market alone exceeds $600 TRILLION.' },
      { who: 'alex', text: 'How does an OTC trade actually happen in practice?' },
      { who: 'finn', text: 'You call a DEALER — typically a large bank like Goldman Sachs. They quote you a bid and ask, you negotiate every term, agree on the details, and sign a legal contract. For large deals, this takes hours of back-and-forth. It\'s nothing like clicking "buy" on an app.' },
      { who: 'alex', text: 'What\'s the downside? If there\'s no exchange guaranteeing the trade...' },
      { who: 'finn', text: 'You\'ve spotted the key risk: COUNTERPARTY RISK. In exchange trading, a CLEARINGHOUSE guarantees every trade — if one party defaults, the clearinghouse covers it. In OTC, if your counterparty goes bankrupt mid-contract, you could lose everything with no safety net.' },
      { who: 'alex', text: 'Isn\'t that basically what happened in the 2008 crisis?' },
      { who: 'finn', text: 'Exactly! AIG had written hundreds of billions in OTC credit derivatives — essentially insurance against mortgage defaults. When housing crashed, AIG couldn\'t pay. But they\'d sold these to EVERY major bank. If AIG failed, the whole financial system collapsed. The US government bailed them out for $182 billion.' },
      { who: 'alex', text: 'Did anything change after 2008 to prevent this?' },
      { who: 'finn', text: 'Yes — major reforms. Dodd-Frank in the US and EMIR in Europe now require most standard OTC derivatives to be cleared through CENTRAL CLEARINGHOUSES (reducing counterparty risk) and reported to regulators (improving transparency). OTC still thrives — but with far more oversight than before.' },
    ],
    concept: 'OTC markets are decentralized — trades happen directly between parties (often via phone/electronic platforms), not on a formal exchange. More flexible but carries counterparty risk. Major OTC markets: bonds, forex, and exotic derivatives.',
    quiz: [
      { q: 'What is "counterparty risk" in OTC trading?', opts: ['Risk that the other party in a deal defaults or can\'t pay', 'Risk of overpaying for an asset', 'The bid-ask spread on OTC trades', 'Government regulation of OTC markets'], ans: 0, exp: 'In OTC trades, there\'s no clearinghouse to guarantee the deal. If your counterparty goes bankrupt mid-contract, you may be left with nothing. This is counterparty risk.' },
      { q: 'Why might a large corporation prefer OTC over an exchange for a $500M interest rate swap?', opts: ['Customizable terms, huge size, no exchange lists such products', 'OTC is always cheaper', 'OTC has faster settlement', 'Regulations require it'], ans: 0, exp: 'OTC allows fully custom contracts — specific notional amounts, payment schedules, reset dates — that standardized exchange products can\'t accommodate. For complex institutional needs, OTC is often the only option.' }
    ]
  },
  {
    id: 'crypto', num: 23, icon: '₿', title: 'Cryptocurrencies',
    tag: 'Digital money and blockchain',
    scene: '₿🔗💻🌐',
    dialogues: [
      { who: 'narrator', text: 'Alex stumbles upon CryptoCorner — the newest district in FinCity. It glows with servers and screens. Everything here is digital, decentralized, and unlike anything Alex has seen before.' },
      { who: 'finn', text: 'Let\'s start from zero. The dollar is money issued by the US government — a central authority controls how many dollars exist and can print more. What if money could exist WITHOUT any government or central authority controlling it?' },
      { who: 'alex', text: 'Is that even possible? Wouldn\'t people just create unlimited fake money?' },
      { who: 'finn', text: 'That was THE key problem Bitcoin solved in 2009! The answer: CRYPTOGRAPHY and decentralization. Instead of one bank keeping the ledger, THOUSANDS of computers worldwide all hold the SAME copy simultaneously. Cheating one copy is useless — you\'d have to cheat 51% of all computers at once.' },
      { who: 'alex', text: 'What\'s a blockchain? Everyone uses that word but nobody explains it.' },
      { who: 'finn', text: 'Imagine a Google Sheet shared with 10,000 computers around the world. Every 10 minutes, a new "page" (BLOCK) of verified transactions gets added. Each page links to the previous one — forming a CHAIN. Once written, a block can NEVER be edited. That permanent, distributed record is the BLOCKCHAIN.' },
      { who: 'alex', text: 'Who decides which transactions get added to the blockchain?' },
      { who: 'finn', text: 'MINERS! Thousands of computers compete to solve a complex math puzzle. The first to solve it earns the right to add the next block — and receives newly created Bitcoin as a reward. This is PROOF OF WORK. It secures the network because attacking it would require more computing power than ALL honest miners combined.' },
      { who: 'alex', text: 'Won\'t miners just keep creating new Bitcoin forever?' },
      { who: 'finn', text: 'No! Bitcoin has a hard cap of 21 MILLION coins — permanently built into the code. Nobody can change this. The reward per block also HALVES approximately every 4 years (called the HALVING). Scarcity is baked in by design, which is why some call Bitcoin "digital gold."' },
      { who: 'alex', text: 'What makes crypto fundamentally different from just using PayPal or Venmo?' },
      { who: 'finn', text: 'Three things: DECENTRALIZATION (no company or government controls it — the network runs itself), PERMISSIONLESS (anyone anywhere can use it with no bank account needed), and PROGRAMMABILITY. Ethereum extends this with SMART CONTRACTS — self-executing code that automatically carries out deals when conditions are met. No humans, no lawyers, just math.' },
      { who: 'alex', text: 'Why does Bitcoin\'s price swing so wildly? It can drop 80% and then rise 1,000%?' },
      { who: 'finn', text: 'Several reasons: it\'s still relatively small (the entire crypto market is tiny vs stocks or bonds), regulation is uncertain and varies by country, it produces no earnings or dividends to anchor its value, and market sentiment dominates pricing. It\'s highly speculative — driven by supply, demand, and belief more than fundamentals.' },
      { who: 'alex', text: 'Should I invest in crypto?' },
      { who: 'finn', text: 'Only what you\'re genuinely comfortable losing entirely. Crypto can be a small part of a diversified portfolio (some suggest 5–10% max for risk-tolerant investors) — but it\'s NOT a replacement for stocks, bonds, or savings. It\'s a high-risk, high-reward bet on an early and still-evolving technology. Never put in money you might need.' },
    ],
    concept: 'Cryptocurrency: decentralized digital currency using blockchain. Blockchain: immutable distributed ledger. Mining: computational work to validate transactions, earns block rewards. Key risks: extreme volatility, regulation, hacks. Key appeal: decentralization, programmability (smart contracts).',
    quiz: [
      { q: 'What is the PRIMARY purpose of a blockchain?', opts: ['A secure, decentralized record of all transactions', 'A faster payment network controlled by banks', 'A type of cryptocurrency', 'An exchange for buying digital assets'], ans: 0, exp: 'Blockchain is the underlying technology — a distributed, immutable ledger. Cryptocurrencies like Bitcoin run ON blockchains, but blockchain itself is a data structure for recording transactions without a central authority.' },
      { q: 'Bitcoin\'s "mining" process serves which function?', opts: ['Validates transactions and secures the network', 'Creates physical coins', 'Pays bank employees', 'Calculates exchange rates'], ans: 0, exp: 'Mining = solving computational puzzles to add verified blocks of transactions to the chain. Miners earn Bitcoin rewards for this work, which simultaneously secures the network against fraud and manipulation.' }
    ]
  }
];
